### ISSUE TITLE
老哥，64位的arm上不能运行

### ISSUE THREAD

**Issue by PHCSJC** [dingguotu/rpi-xware#1]
斐讯N1刷的armbian，64位的arm架构，按你的教程获取不到激活码，老哥这个怎么解决呢？ 
root@aml:~# cat /etc/issue
Debian GNU/Linux 9 \n \l

root@aml:~# lsb_release -a
No LSB modules are available. Distributor ID:	Debian Description: Debian GNU/Linux 9.5 (stretch) Release:	9.5 Codename:	stretch

root@aml:~# uname -a
Linux aml 4.18.7-aml-s9xxx #1 SMP PREEMPT Fri Nov 23 22:10:11 CST 2018 aarch64 GNU/Linux

root@aml:/opt/xunlei# ./portal 
initing...

try stopping xunlei service...

setting xunlei runtime env...
port: 9000 is usable.

YOUR CONTROL PORT IS: 9000

starting xunlei service...
execv: /opt/xunlei/lib/ETMDaemon.

getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 1 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 2 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 3 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 4 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 5 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 6 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 7 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 8 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 9 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 10 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 11 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 12 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 13 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 14 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 15 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 16 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 17 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 18 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.

try again...(has tried 19 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
xunlei_portal.tmp        0T --:--:-- ETA
the active key is not valid.
fail to get xunlei service info finaly.
finished.

**Comment by tellok** [comment]
我用的64位树莓派可以啊，感觉你这个应该是网络不通，无法从迅雷服务器拉去激活码
